baseURL = ""
languageCode = "en-us"
title = "The Krystal Ship"
theme = "methlab"
copyright = "2018"
languagecode = "en" # The site’s language code used to generate RSS.
defaultcontentlanguage = "en" # The default content language.
enableEmoji = true # :100:
enableRobotsTXT = true # Help google out a bit
refLinksNotFoundURL = "404.html" # Use custom 404 page

paginate = 20 # Default number of pages per page in pagination.
canonifyurls = true # Enable to turn relative URLs into absolute.

pygmentsstyle = "b2" # Color-theme or style for syntax highlighting.
pygmentscodefences = true # Enable code fence background highlighting.
pygmentscodefencesguesssyntax = true # Enable syntax guessing for code fences without specified language.

disqusShortname = "thekrystalship-org" # Enable or disable Disqus.

[params] # theme parameters
    subtitle = "Under Construction" # Author's job title or info.
    description = "The Krystal Ship organization website" # Site description.
    keywords = "blog,developer,personal,coding" # Site keywords.
    avatarurl = "images/logo.svg" # Contain the path of the optional avatar in the static folder.

    # Multilanguage mode
    langseparator = "|" # Separates menus from language selectors when site is multilingual.

    customCssFiles = ["styles/index.css"] # Load custom css file
    customJsFiles = ["scripts/index.js"] # Load custom scripts
    favicons = []

# Social links
[[params.social]]
    name = "Github"
    weight = 1
    url = "https://github.com/TheKrystalShip/"
[[params.social]]
   name = "Discord"
   weight = 2
   url = "https://discord.gg/pvm9NAv"

# Navbar links
[[menu.navbar]]
    name = "Projects"
    weight = 1
    url  = "/projects/"
[[menu.navbar]]
    name = "Categories"
    weight = 2
    url = "/categories/"
[[menu.navbar]]
    name = "Developers"
    weight = 3
    url = "/developers/"
[[menu.navbar]]
    name = "About"
    weight = 4
    url = "/about/"

