baseURL = "https://thekrystalship.org"
languageCode = "en-us"
title = "The Krystal Ship"
theme = "hugo-coder"
languagecode = "en" # The site’s language code used to generate RSS.
defaultcontentlanguage = "en" # The default content language.

paginate = 20 # Default number of pages per page in pagination.
canonifyurls = true # Enable to turn relative URLs into absolute.

pygmentsstyle = "b2" # Color-theme or style for syntax highlighting.
pygmentscodefences = true # Enable code fence background highlighting.
pygmentscodefencesguesssyntax = true # Enable syntax guessing for code fences without specified language.

disqusShortname = "thekrystalship-org" # Enable or disable Disqus.

[params] # theme parameters
    author = "The Krystal Ship" # Author's name.
    # info = "" # Author's job title or info.
    description = "The Krystal Ship organization website" # Site description.
    keywords = "blog,developer,personal,coding" # Site keywords.
    avatarurl = "images/logo.png" # Contain the path of the optional avatar in the static folder.

    # footercontent = "Enter a text here." # Add footer content

    # Whether you want to hide copyright and credits in the footer.
    hideCopyright = false

    # Custom CSS
    custom_css = []

    # RTL support
    rtl = false

    # Multilanguage mode
    langseparator = "|" # Separates menus from language selectors when site is multilingual.

# Social links
[[params.social]]
    name = "Github"
    weight = 1
    url = "https://github.com/TheKrystalShip/"
[[params.social]]
   name = "Discord"
   weight = 2
   url = "https://discord.gg/pvm9NAv"
#[[params.social]]
#    name = "LinkedIn"
#    weight = 3
#    url = "https://www.linkedin.com/in/johndoe/"

# Menu links
[[menu.main]]
    name = "Projects"
    weight = 1
    url  = "/projects/"
[[menu.main]]
    name = "Categories"
    weight = 2
    url = "/categories/"
[[menu.main]]
    name = "Developers"
    weight = 3
    url = "/developers/"
[[menu.main]]
    name = "About"
    weight = 4
    url = "/about/"

